import { Inter, Poppins } from 'next/font/google';
import './globals.css';

import { AppContextProvider } from '@/app/contexts/AppContext';
import Navbar from '@/app/components/Navbar';
import Footer from '@/app/components/Footer';
import InfoSection from './components/InfoSection';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter'});
const poppins = Poppins({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], variable: '--font-poppins'});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} ${poppins.variable}`}>
        <AppContextProvider>
          <Navbar />
          {children}
          <InfoSection />
          <Footer />
        </AppContextProvider>
      </body>
    </html>
  );
}
